runtime: python27
api_version: 1
threadsafe: yes
automatic_scaling:
  min_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: 1500ms
  max_concurrent_requests: 20
env_variables:
  PYTHONHTTPSVERIFY: 1

skip_files:
- ^(.*/)?.*\.pyc$

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /
  secure: always
  redirect_http_response_code: 301
  script: main.app
- url: /_styles
  secure: always
  static_dir: static/_styles
- url: /_scripts
  secure: always
  static_dir: static/_scripts
- url: /_images
  secure: always
  static_dir: static/_images
- url: /_/api/users.*
  secure: always
  script: modules.users.handlers.app
- url: /_/api/links.*
  secure: always
  script: modules.links.handlers.app
- url: /_/auth/.*
  secure: always
  script: modules.base.handlers.app
- url: .*
  secure: always
  script: modules.routing.handlers.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: ssl
  version: "2.7.11"

builtins:
- deferred: on
